name: hugo push to github pages

on:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/blog'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: HUGO_ENV=production hugo --gc --minify
        
  deploy:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
